---
fullname: Gaia
shortname: gaia
organization: coq-community
community: true
dune: false
action: true

synopsis: Implementation of books from Bourbaki's Elements of Mathematics in Coq

description: |-
  Implementation of books from N. Bourbaki's Elements of Mathematics
  in Coq using the Mathematical Components library, including set theory
  and number theory.

build: |-
  ## Building and installation

  To build and install manually, do:
  
  ``` shell
  git clone https://github.com/coq-community/gaia.git
  cd gaia
  make   # or make -j <number-of-cores-on-your-machine> 
  make install
  ```

publications:
- pub_url: https://jfr.unibo.it/article/view/1899
  pub_title: "Implementation of Bourbaki's Elements of Mathematics in Coq: Part One, Theory of Sets"
  pub_doi: 10.6092/issn.1972-5787/1899
- pub_url: https://jfr.unibo.it/article/view/4771
  pub_title: "Implementation of Bourbaki's Elements of Mathematics in Coq: Part Two, From Natural Numbers to Real Numbers"
  pub_doi: 10.6092/issn.1972-5787/4771
- pub_url: https://hal.inria.fr/inria-00408143
  pub_title: "Implementation of Bourbaki's Elements of Mathematics in Coq: Part One, Theory of Sets"
- pub_url: https://hal.inria.fr/inria-00440786
  pub_title: "Implementation of Bourbaki's Elements of Mathematics in Coq: Part Two; Ordered Sets, Cardinals, Integers"
- pub_url: https://hal.inria.fr/hal-01412037
  pub_title: "Implementation of Bourbaki's Elements of Mathematics in Coq: Part Three Structures"
- pub_url: https://hal.inria.fr/hal-01093589
  pub_title: "Fibonacci numbers and the Stern-Brocot tree in Coq"
- pub_url: https://hal.inria.fr/hal-00911710
  pub_title: "Implementation of three types of ordinals in Coq"

authors:
- name: José Grimm
- name: Alban Quadrat
- name: Carlos Simpson

maintainers:
- name: Laurent Théry
  nickname: thery

opam-file-maintainer: palmskog@gmail.com

opam-file-version: dev

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: '8.10 or later'
  opam: '{(>= "8.10" & < "8.16~") | (= "dev")}'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{(>= "1.12.0" & < "1.14~") | (= "dev")}'
  description: |-
    [MathComp ssreflect 1.12 or later](https://math-comp.github.io)
- opam:
    name: coq-mathcomp-algebra
  description: |-
    [MathComp algebra](https://math-comp.github.io)

tested_coq_opam_versions:
- version: 'coq-dev'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.15'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.14'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.13'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.12'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.11'
  repo: 'mathcomp/mathcomp-dev'
- version: '1.13.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.12'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.11'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.12'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.11'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.10'
  repo: 'mathcomp/mathcomp'

namespace: gaia

keywords:
- name: Bourbaki
- name: set theory
- name: ordinals
- name: cardinals

categories:
- name: Mathematics/Logic/Set theory
- name: Mathematics/Arithmetic and Number Theory/Number theory

documentation: |-
  ## Documentation

  Gaia stands for: Geometry, Algebra, Informatics and Applications.
  More information about the project is available at the [project website][gaia-url].

  [gaia-url]: http://www-sop.inria.fr/marelle/gaia/
---
